# -*- coding: utf-8 -*-
"""clase1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18-pvDrT4UxEovC9QvqEnV5tvKwd54dWW
"""

import math
p = math.pi

def perimetro_rectangulo(base,altura):
  perimetro_rectangulo = base*2 + altura*2
  return perimetro_rectangulo

def area_rectangulo (base,altura):
  area_rectangulo = base * altura
  return area_rectangulo

def perimetro_circulo (radio):
  perimetro_circulo = 2*p * radio
  return perimetro_circulo

def area_circulo (radio):
  area_circulo = p* radio**2
  return area_circulo

def perimetro_cuadrado (lado):
  perimetro_cuadrado = 4*lado
  return perimetro_cuadrado

def area_cuadrado (lado):
  area_cuadrado = lado*lado
  return area_cuadrado

perimetro_cuadrado(5)
area_cuadrado(5)

perimetro_rectangulo(20,15)
area_rectangulo(20,15)

perimetro_circulo(32)
area_circulo(32)